# Generated by Django 4.1.5 on 2023-01-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Store", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
